min_trimmed_length = 6
min_word_count = 2
max_word_count = 15
min_characters = 6
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
disallowed_symbols = [
  '<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/', '=',
  'Å', 'Ł', 'ś', 'ń', 'ź', 'ñ', 'š', 'ö', 'â', 'ë', 'ä', 'ê', 
  'α', 'β', 'Γ', 'γ', 'Δ', 'δ', 'ε', 'ζ', 'η', 'Θ', 'θ', 'ι', 'κ',
  'Λ', 'λ', 'μ', 'ν', 'Ξ', 'ξ', 'Π', 'π', 'ρ', 'Σ', 'σ', 'ς', 'τ',
  'υ', 'Φ', 'φ', 'χ', 'Ψ', 'ψ', 'Ω', 'ω',
  'ム',
  '$', '€', 
  'б', 'м', 'ы', 'л',
  '"', '«', '»', '“', '”', '„', '“', '•', '‘'
]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
abbreviation_patterns = [
  "[A-Z]+\\.* ?[A-Z]",
  "[A-Z][A-Z]+",
  "[\\s'‘][A-Z]\\b",
  "aC", "dC",
  " ex\\.",
  " .\\.",
  "\\..",
  "[;,]$",
  "El següent diagrama mostra les poblacions més properes\\.",
  "És inofensiu per als humans\\.",
  "Ha estat doblada al català\\.",
  "Es troba amenaçada d'extinció per la pèrdua del seu hàbitat natural\\.",
  "Està amenaçada d'extinció per la pèrdua del seu hàbitat natural\\.",
  "És un peix d'aigua dolça i de clima tropical\\.",
  "Viu en zones de clima tropical\\.",
  "Cristal·litza en el sistema monoclínic\\.",
  "És ovípar\\.",
  "Cap de les famílies estaven per davall del llindar de pobresa\\.",
  "Cristal·litza en el sistema ortoròmbic\\.",
  "És un fragment de la llista d'asteroides completa\\.",
  "Es troba a la Xina\\."
]
