min_trimmed_length = 3
min_word_count = 1
max_word_count = 14
min_characters = 1
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = false
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

allowed_symbols_regex = "[\u0020A-Za-z\"„“‚‘’–\\.?!()]"
even_symbols = ['"']
matching_symbols = [
  ["„", "“"],
  ["(", ")"]
]

# Abbreviation examples for each regex
#   - A.B or FBI
abbreviation_patterns = [
  "[A-Z]+\\.*[A-Z]"
]

# Other patterns
#   - Sentence delimiter can only be at the end of a sentence
#   - No words with only one letter (" a.", " a", " a ")
#   - Mixed upper/lowercase in words (LaSi - mostly chemical elements?)
other_patterns = [
  "[\\.|\\?|!].+$",
  "(\\s[A-Za-z]{1}[\\.|\\?|!]*$)|\\s[A-Za-z]{1}\\s",
  "[a-z][A-Z][a-z]",
]
