min_trimmed_length = 3
min_word_count = 1
max_word_count = 14
min_alphanumeric_characters = 0
may_end_with_colon = false
quote_start_with_alphanumeric = true
needs_punctuation_end = false
needs_alphanumeric_start = true
needs_uppercase_start = false
disallowed_symbols = ['<', '>', '+', '*', '\\', '#', '@', '^', '[', ']', '(', ')', '/', '\n']
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
abbreviation_patterns = ??????
