min_trimmed_length = 5
min_word_count = 3
max_word_count = 14
min_characters = 2
may_end_with_colon = true
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = false
needs_uppercase_start = false
disallowed_symbols = [
  '<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/', '=',
  'Ł', 'ś', 'ń', 'ź', 'ñ', 'š', 
  'α', 'β', 'Γ', 'γ', 'Δ', 'δ', 'ε', 'ζ', 'η', 'Θ', 'θ', 'ι', 'κ',
  'Λ', 'λ', 'μ', 'ν', 'Ξ', 'ξ', 'Π', 'π', 'ρ', 'Σ', 'σ', 'ς', 'τ',
  'υ', 'Φ', 'φ', 'χ', 'Ψ', 'ψ', 'Ω', 'ω',
  'ム', 'בְ', 'ɛ', 'ɔ',
  '$', '€', '&',
  'б', 'м', 'ы', 'л',
  '"', '«', '»', '“', '”', '„', '“', '•', '‘', '’',
  'Ã', 'Å', 'Ä', 'Ë', 'Ï', 'Ö', 'Ü',
  'Á', 'É', 'Í', 'Ó', 'Ú',
  'á', 'é', 'í', 'ó', 'ú', 'ä', 'ë', 'ï', 'ö', 'ü',
  'â', 'ê', 'î', 'ô', 'û', 'à', 'è', 'ì', 'ò', 'ù',
  'Ç', 'ç', '§', '©', '½', '¾', '³', '‰', 'ː',
  'щ', 'з', 'и', 'к', 'ʻ'
]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
abbreviation_patterns = [
  "[A-Z][A-Z]+",
  "[A-Z]+\\.* ?[A-Z]",
  "adib\\.",
  "K\\. o\\.|K\\. a\\.|K\\.o\\.|K\\.a\\.|k\\.o\\.|k\\.a\\.",
  "[;,]$",
  "[IVX].",
  "[Qq]ue", 
  "\\-de\\-",
  "[Hh]aute\\-",
  "Saint\\-",
  "idae|mp|ph|ch|nn|elec|ally" 
  ]
